[package]
name = "tinygraph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.29.0"
byteorder = "1.0.0"
libdeflater = "0.14.0"
clap = { version = "4.3.0", features = ["derive"] }
